{
  "formatVersion": "1.1",
  "component": {
    "group": "josie.blockgamekeyvalue",
    "module": "blockgamekeyvalue",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "blockgamekeyvalue-0.1.0.jar",
          "url": "blockgamekeyvalue-0.1.0.jar",
          "size": 5616,
          "sha512": "ba844a291011838dc840438b9e2c1f9738fa5b2c049ad5bfbc32b52076c43408f91a78a3137db77781c410767692d186bdb1b5dbb04004b5b901d142f8940e2d",
          "sha256": "63aa18e8480eb1555092e4268833cff2ab865df67961930937dfa8090dca38e8",
          "sha1": "b61188aea241b871bcb36a188a5a1d23a7c97eed",
          "md5": "d9c108365a7dd154760d674c02eab167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "blockgamekeyvalue-0.1.0.jar",
          "url": "blockgamekeyvalue-0.1.0.jar",
          "size": 5616,
          "sha512": "ba844a291011838dc840438b9e2c1f9738fa5b2c049ad5bfbc32b52076c43408f91a78a3137db77781c410767692d186bdb1b5dbb04004b5b901d142f8940e2d",
          "sha256": "63aa18e8480eb1555092e4268833cff2ab865df67961930937dfa8090dca38e8",
          "sha1": "b61188aea241b871bcb36a188a5a1d23a7c97eed",
          "md5": "d9c108365a7dd154760d674c02eab167"
        }
      ]
    }
  ]
}
